neutral-description = Freelancers, vagabonds, mercenaries, pirates, all under no flag. No loyalty to any nation, operating solely for themselves or for their respective organizations. Who knows how any one of them got into the Colossus sector? No one wonders that, because it doesn't matter. Peaceful merchants or hostile gunmen, they're here either way.

tsf-description = The strongest galactic superpower ever known, only potentially rivalled by the splinter faction the Coalition of Outer Rim Systems. Based out of their capital of Caligo Prime, the Federation came to power after the end of the Corporate Wars, filling in the power vacuum left behind in the wake of Nanotrasen's fall. Although public opinion was, and is generally good, their policies have caused a constant civil unrest to the point of causing the Federation's first civil war, creating the USSP and CORS. A notable amount of settlers affiliated with the TSF have been in the Colossus sector since it was first mapped by the TSF, but as of recent most of the TSF population in-sector is military due to the ongoing war with the PDV and the CORS blockade preventing exit.

pdv-description = Not much is known about the Phaethon Dynasty in modern times, but it is theorized they originated from remnants of shattered Syndicate fleets, having fled into the outer rim to avoid prosecution for their deeds. Over time, more and more of them banded together under a new flag, a new culture, a new ruler: their ever-mysterious Sultan. Much of their technology is still the same outdated, red-tinted syndicate tech their distant ancestors before them would have been using to massacre Nanotrasen workers, now used by militaristic fanatics in the service of the Sultan. Their forces in Colossus find themselves in the same trap the Federation forces they are at war with fell into, blockaded and trapped in the sector by the Coalition blockade.

ussp-description = Fragments of a once far more powerful galactic power, what remains of the Union of Soviet Socialist Planets desperately clings on to the territories they have left amidst constant harassment from the Trans-Solar Federation, Royal Commonwealth of Man and Coalition of Outer Rim Systems for various reasons. Their capital, Nova Cygni, is one of the very few places these remnants can have any semblance of peace. Many military and civillian assets were abandoned in the Colossus sector as the union withdrew amidst growing instability in the homeland, and that is the main reason some citizens of the USSP may find themselves in Colossus.

cors-description = A massive, corporate-backed splinter group of the Federation, having formed during the TSF's first civil war with insane corporate backing pushing the Coalition of Outer Rim Systems to quickly rival the Federation's power. Despite all their immense military strength and high technology, the Coalition doesn't make any major invasion into Federation space, choosing instead to entrench themselves in the outer rim of known space even further with each passing year. Their capital world in the Hyphes system is their core, their most defended territory, and kept completely unknown to all other nations through a mix of counterintelligence, subterfuge, and occasionally demonstrations of raw strength. Coalition military forces have recently completely blockaded the entire Colossus sector, preventing the Federation military forces within from leaving.

rcm-description = A partially isolated nation, residing in their small territories relatively close to the Federation's core. Proudly descended from early space expeditions done by the now long gone United Kingdom, these proud people of the Royal Commonwealth of Man held on to the same culture their distant ancestors did, though of course not perfectly. For what they lack in numbers, they make up for with their deceptively well crafted technology. Despite much of their arsenal and equipment looking like it's ripped straight from ancient Terran history, they have perfected their craftsmanship over hundreds of years and added new innovations underneath the old, creating some of known spaces most powerful, dangerous equipment. Closely allied with Dornan-Weryl Industrial, as the company works out of RCM space and closely with their military and government.


